### PR TITLE
convert to pep8 and pytest

### PR DESCRIPTION
**Pull request by chsasank**
converted all tests to simple pytest. 

Some tests are failing. @erezsh: Can you edit them?

```
(base) [~/test/omnidoc/omnidoc]$ pytest
======================== test session starts ========================
platform darwin -- Python 3.6.9, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/Sasank/test/omnidoc/omnidoc
plugins: devpi-server-5.0.0, django-3.5.1, cov-2.7.1
collected 3 items                                                   

tests/test_markdown.py .                                      [ 33%]
tests/test_types.py .                                         [ 66%]
tests/test_typesystem.py F                                    [100%]

============================= FAILURES ==============================
______________________ test_simple_type_system ______________________

    def test_simple_type_system():
        t1 = TreeType(Tree, frozenset({'a', 'b', 'c'}))
>       assert not (t1 <= UnknownTree())

tests/test_typesystem.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/omnidoc/typesystem.py:19: in __le__
    return self.issubtype(other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = TreeType(name=<class 'omnidoc.tree.Tree'>, nodeset=frozenset({'b', 'c', 'a'}))
t = <test_typesystem.UnknownTree object at 0x109506208>

    def issubtype(self, t):
>       assert isinstance(t, TreeType), t
E       AssertionError: <test_typesystem.UnknownTree object at 0x109506208>

tests/omnidoc/typesystem.py:14: AssertionError
================ 1 failed, 2 passed in 0.11 seconds =================
```

### CODE REVIEW

**Comment by erezsh** [comment]
I'm getting 

```
ImportError while importing test module 'C:\code\omnidoc\tests\test_markdown.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_markdown.py:1: in <module>
    import omnidoc
E   ModuleNotFoundError: No module named 'omnidoc'
```

**Comment by erezsh** [comment]
Happens when I do

    pytest

But this is working fine:

    python -m pytest

**Comment by chsasank** [comment]
One sec. Lemme create symlink.

**Comment by chsasank** [comment]
It's already there. Make sure `tests/omnidoc` is symlinked to `omnidoc`. If so, `pytest` should work fine.

**Comment by erezsh** [comment]
I'm working on Windows 🤡

**Comment by erezsh** [comment]
So should I merge it?

**Comment by chsasank** [comment]
merged

**Comment by chsasank** [comment]
> I'm working on Windows 🤡

Highly recommend WSL! v2 in particular. It's epic.

**Pull request merged**
